name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image name
      id: image_name
      run: |
        repository=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')
        echo "image_name=ghcr.io/$repository" >> $GITHUB_OUTPUT

    - name: Build and push to repository
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ steps.image_name.outputs.image_name }}:${{ github.sha }}